import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/store/authContext'
import {Provider} from 'react-redux'
import store from '@/store/store'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Netnaija Flix',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <Provider store={store}>
      <AuthProvider>
      <body className={inter.className} suppressHydrationWarning={true}>{children}
      </body> 
      </AuthProvider>
      </Provider>
    </html>
  )
}
